spring:
  application:
    name: PIGGYBANK-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
        - id: piggybank-creditcard-service
          uri: lb://PIGGYBANK-CREDITCARD-SERVICE
          predicates:
          - Path=/piggybank/creditcard/**

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
